eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka   
server:
  port: 8091
spring:
  application:
    name: spring-gateway-server
  config:
    import:
    - configserver:http://localhost:8888
  profiles:
    active:
    - dev
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  cloud:
    gateway:
      routes:
      - id: servicio-alumnos
        uri: lb://servicio-alumnos
        predicates:
        - Path=/api/alumnos/**
        filters:
         - StripPrefix=2