server:
  port: 8091
spring:
  application:
    name: spring-gateway-server
  cloud:
    gateway:
      routes:
      - id: servicio-alumnos
        uri: lb://servicio-alumnos 
        predicates:
          - Path=/api/alumnos/**
        filters:
          - StripPrefix=2 ##por el api y por alumnos 
